### ISSUE TITLE
Grandle & JSON file

### ISSUE THREAD

**Issue by blondie63** [ionicfirebaseapp/flutter-app#1]
On your docs:
https://docs.ionicfirebaseapp.com/todo/installation-guide
i read:
If you notice Gradle task assembly debug failed with exit code one error make sure to place JSON file inside the src>android>app folder and run flutter run and your application gets installed.

But, which JSON file ?
Running app with flutter run i've this error:
* Error running Gradle:
ProcessException: Process "/Users/mauro/Documents/_projects/Flutter/flutter-app-TODO-master/android/gradlew" exited abnormally:
Starting a Gradle Daemon (subsequent builds will be faster)
  Command: /Users/mauro/Documents/_projects/Flutter/flutter-app-TODO-master/android/gradlew app:properties
How can i fix it ?

**Comment by pietechsolution** [comment]
We have updated our docs, please check you need to add your firebase service JSON file.

**Comment by blondie63** [comment]
what's the right path to move file google-services.json?
your guide is still wrong !
ps. i've bought some your other products hoping your support will be better..
<img width="1495" alt="ionicfirebase-todo-android" src="https://user-images.githubusercontent.com/1261851/69914997-79b10080-144a-11ea-8d95-15ccfef645ad.png">
